add nvmrc and update ssh.yml

diff --git a/.github/workflows/ssh.yml b/.github/workflows/ssh.yml
--- a/.github/workflows/ssh.yml
+++ b/.github/workflows/ssh.yml
@@ -1,31 +1,36 @@
 name: Continuous Deployment via SSH
 on:
-  [workflow_dispatch]
+  workflow_dispatch: # Allows manual triggering of the workflow
+  # Uncomment the following lines to enable automatic deployment on push to the main branch
   # push:
-  #  branches:
-  #   - main
+  #   branches:
+  #     - main
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
-
-    strategy:
-      matrix:
-        node-version: [18.x, 20.x]
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
 
       - name: Install SSH Key
+        env:
+          DEPLOYUSERSSHKEY: ${{ secrets.DEPLOYUSERSSHKEY }}
         run: |
           mkdir -p ~/.ssh/
-          echo "${{ secrets.DEPLOYUSERSSHKEY }}" > ~/.ssh/id_rsa
+          echo "$DEPLOYUSERSSHKEY" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
+
+      - name: Add SSH Key to SSH Agent
+        run: |
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/id_rsa
 
       - name: Execute Deployment Commands
         run: |
           ssh -o StrictHostKeyChecking=no deployuser@44.238.195.106 << 'EOF'
+            set -e # Exit immediately if a command exits with a non-zero status
             source ~/.profile || true
             source ~/.bashrc || true
             # Ensure you're in the correct directory
@@ -34,7 +39,10 @@ jobs:
             git pull origin main
             # Activate the Node.js version managed by nvm
             source ~/.nvm/nvm.sh
-            nvm use ${{ matrix.node-version }}
+            # Read the Node.js version from .nvmrc
+            NODE_VERSION=$(cat .nvmrc)
+            nvm install $NODE_VERSION
+            nvm use $NODE_VERSION
             # Install any new dependencies using npm from nvm
             npm install
             # Build the project
